update Sklearn Basic 3 to illustrate entities
KhiopsML/khiops-python-tutorial pull request #2
Opened 2024-02-27 14:48 UTC by nairbenrekia

2024-02-27 18:20 UTC, folmos-at-orange requested changes
Minor stuff.

2024-02-27 18:20 UTC, folmos-at-orange commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "  - The key of ``table1`` is contained in that of ``table2`` (ie. keys are hierarchical)\n",
I'd add some small changes:
- "The first two values (`str`) ... " 
- "A third value (`bool`) can be optionally set as `True` to indicate that the relation is `1:1`.
- "For example, **If** the ..." -> "For example, **if** the ..." (lower case)

2024-02-27 18:20 UTC, folmos-at-orange commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "If the ``relations`` field is not present then Khiops Python assumes that the tables are in a *star* schema."
I'd add : "... *star* schema with `main_table` as the central table."

2024-02-27 18:20 UTC, folmos-at-orange commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "- The tertiary table `Users` which has a 1:n relationship with `Vehicles`.\n"
I'd put `1:1` with backticks ``` `1:1` ```. Similarly with `1:n`

2024-02-28 11:37 UTC, nairbenrekia commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "- The tertiary table `Users` which has a 1:n relationship with `Vehicles`.\n"
Ok.

2024-02-28 11:38 UTC, nairbenrekia commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "If the ``relations`` field is not present then Khiops Python assumes that the tables are in a *star* schema."
Ok.

2024-02-28 11:38 UTC, nairbenrekia commented on Sklearn Basics 3 - Train a Classifier on a Snowflake Multi-Table Dataset.ipynb
> +    "  - The key of ``table1`` is contained in that of ``table2`` (ie. keys are hierarchical)\n",
Ok.

2024-02-28 13:41 UTC, folmos-at-orange approved these changes

2024-02-28 13:59 UTC, merged